const protectedPostConfig = {
  title: "Posts",
  descriptionUpdate: "Update your post",
  description: "Manage your posts",
  delete: "Delete",
  edit: "Edit",
  update: "Update",
  questionDelete: "Are you sure you want to delete this post?",
  warning: "This action cannot be undone.",
  cancel: "Cancel",
  confirm: "Confirm",
  tableHeader: ["Post", "Date", "Action"],
  updatePost: "Update post",
  newPost: "New Post",
  successDelete: "Post deleted.",
  successCreate: "Post created.",
  successUpdate: "Post updated.",
  errorCreate: "Couldn't create post.",
  errorDelete: "Couldn't delete post.",
  errorUpdate: "Couldn't update post.",
  author: "Author",
  pleaseWait: "Please wait...",
  untitled: "Untitled",
  publish: "Publish",
  successPublish: "Post published successfully.",
  errorPublish: "Couldn't publish post.",
  unpublish: "Unpublish",
  successUnpublish: "Post unpublished. It is now a draft.",
  errorUnpublish: "Couldn't unpublish post.",
  viewPublished: "View post",
};

export default protectedPostConfig;
